spring.application.name=hive2home

spring.datasource.url=jdbc:postgresql://localhost:5432/hive2home
spring.datasource.username=postgres
spring.datasource.password=RajToshi321$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080